'use strict';
const { test } = require('node:test');
const assert = require('node:assert/strict');
const { detectAiTool, detectFramework } = require('../lib/fingerprint.js');

test('detectAiTool identifies v0 from HTML comment', () => {
  assert.equal(detectAiTool('<!-- Generated by v0 by Vercel --><html>'), 'v0');
});

test('detectAiTool identifies Lovable from HTML comment', () => {
  assert.equal(detectAiTool('<!-- Built with Lovable --><html>'), 'Lovable');
});

test('detectAiTool returns null for unknown tools', () => {
  assert.equal(detectAiTool('<html><body>hand written</body></html>'), null);
});

test('detectFramework identifies Next.js from header', () => {
  assert.equal(detectFramework('', { 'x-powered-by': 'Next.js' }), 'Next.js');
});

test('detectFramework identifies SvelteKit from HTML', () => {
  assert.equal(detectFramework('window.__sveltekit_data = {};', {}), 'SvelteKit');
});

test('detectFramework returns Static for no signals', () => {
  assert.equal(detectFramework('<html></html>', {}), 'Static');
});
