// fingerprints.js
// HTML comment signatures only (v1). CSS/JS patterns produce false positives.
// Add new signatures via PR - see CONTRIBUTING.md
'use strict';

const AI_TOOLS = [
  { name: 'v0',       pattern: /<!--[\s\S]*?Generated by v0/i },
  { name: 'Bolt',     pattern: /<!--[\s\S]*?Built with Bolt/i },
  { name: 'Lovable',  pattern: /<!--[\s\S]*?Built with Lovable/i },
  { name: 'Cursor',   pattern: /data-cursor-generated/i },
  { name: 'Claude',   pattern: /<!--[\s\S]*?Generated by Claude/i },
  { name: 'Windsurf', pattern: /<!--[\s\S]*?Built with Windsurf/i },
];

const FRAMEWORKS = [
  { name: 'Next.js',   headerKey: 'x-powered-by', headerVal: /next\.js/i },
  { name: 'Next.js',   htmlPattern: /__NEXT_DATA__/i },
  { name: 'Nuxt',      htmlPattern: /__nuxt/i },
  { name: 'SvelteKit', htmlPattern: /__sveltekit_data/i },
  { name: 'Remix',     htmlPattern: /window\.__remixContext/i },
  { name: 'Astro',     htmlPattern: /\/_astro\//i },
];

module.exports = { AI_TOOLS, FRAMEWORKS };
